name: Deploy Package to Github Registry

on:
  push:
    branches:
      - main

jobs:
  PublishToGithubPackageRegistry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm run build
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
