name: Publish New Version of DesignSystem to NPM

on:
  push:
    branches:
      - main

jobs:
  Publish-New-DesignSystem-Version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to install and publish the repository."
      - run: npm install
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm run build
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: echo "This job's status is ${{ job.status }}."
