name: Publish New Version of DesignSystem to NPM
on: [push]
jobs:
  Publish-New-DesignSystem-Version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to install and publish the repository."
      - name: Pre-Publish Commands
        run: |
          npm install
          npm run build
      - run: npm publish
      - run: echo "This job's status is ${{ job.status }}."